policy_type: "parkour_moe_engine"
policy_path: "/home/unitree/3-21-MOE-SIM2REAL/deploy/pre_train/go2/parkour_moe_inference_bundle.pt"
engine_dir: "/home/unitree/3-21-MOE-SIM2REAL/deploy/deploy_real/go2_trt_engines_40_1"
engine_precision: "fp16"
device: "cpu"

control_dt: 0.02

msg_type: "go"
imu_type: "torso"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

joint2motor_idx: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]

kps: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]
kds: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

#kps: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
#kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

default_angles: [0.1, 0.8, -1.5,
                 -0.1, 0.8, -1.5,
                  0.1, 1.0, -1.5,
                 -0.1, 1.0, -1.5]

obs_scales_ang_vel: 0.25
obs_scales_dof_pos: 1.0
obs_scales_dof_vel: 0.05
command_scale: [2.0, 2.0, 0.25]
action_scale: 0.25

num_actions: 12
num_obs: 45
cmd_init: [0.8, 0.0, 0.0]

camera:
  update_interval: 5
  buffer_len: 2
  output_height: 58
  output_width: 87
  clipping_range: 2.0
  enable_selector: false
  selector_threshold: 0.001
  image_path: ""
  ros2_enabled: true
  ros2_topic: "/forward_depth_image"
  ros2_msg_type: "float32_multi_array"
  ros2_initial_wait_sec: 2.0
  ros2_frame_timeout_sec: 0.5

blind_walk:
  enabled: true
  toggle_button: "F1"
  image_path: ""
  random_seed: 1234
  randomize_each_refresh: false
